spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  spring:
    h2:
      console.enabled: false

logging:
  path: logs
  level:
    org:
      springframework:
        web: DEBUG

authentication:
  username: 'user123'
  password: '{noop}P@ssw0rd'




